name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: semantic release
        uses: ridedott/release-me-action@v1
        with:
          dry-run: true
          node-module: true
          release-rules:
            '[{ "release": "patch", "type": "docs" }, { "release": "patch", "type":
            "chore" }, { "release": "patch", "type": "perf" }, { "release": "patch", "type": "test" },
            { "release": "patch", "type": "refactor" }]'